# cloudbuild.yaml — manual-build friendly (uses ${BUILD_ID} which always exists)

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
timeout: "1200s"

steps:
# 1) Build
- name: gcr.io/cloud-builders/docker
  args: ["build","-t","europe-west2-docker.pkg.dev/$PROJECT_ID/innerpeace/innerpeace-api:${BUILD_ID}","."]

# 2) Push
- name: gcr.io/cloud-builders/docker
  args: ["push","europe-west2-docker.pkg.dev/$PROJECT_ID/innerpeace/innerpeace-api:${BUILD_ID}"]

# 3) Deploy (use the same tag)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -ceu
    - |
      gcloud run deploy innerpeace-api \
        --region europe-west2 \
        --image "europe-west2-docker.pkg.dev/$PROJECT_ID/innerpeace/innerpeace-api:${BUILD_ID}" \
        --service-account "run-innerpeace-sa@$PROJECT_ID.iam.gserviceaccount.com" \
        --port 8080 \
        --min-instances 1 \
        --max-instances 20 \
        --concurrency 80 \
        --timeout 240 \
        --update-env-vars "AUTH_MODE=keyless-dwd" \
        --set-secrets "CALENDAR_ID=CALENDAR_ID:latest,GOOGLE_DELEGATED_USER=GOOGLE_DELEGATED_USER:latest,USE_MEET=USE_MEET:latest" \
        --allow-unauthenticated

images:
- "europe-west2-docker.pkg.dev/$PROJECT_ID/innerpeace/innerpeace-api:${BUILD_ID}"
