# cloudbuild.yaml — SECRET lane
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
timeout: "1200s"

steps:
  - id: build-and-push
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -ceu
      - |
        set -o pipefail
        TAG="${SHORT_SHA:-${BUILD_ID:-local-$(date +%s)}}"
        PROJECT="${PROJECT_ID}"
        REGION="europe-west2"
        REPO="innerpeace"
        SERVICE="innerpeace-api"
        IMG="${REGION}-docker.pkg.dev/${PROJECT}/${REPO}/${SERVICE}:${TAG}"
        echo "Building ${IMG}"
        docker build -t "${IMG}" .
        docker push "${IMG}"
        printf '%s' "${IMG}" > /workspace/IMG.txt

  # Remove any literal mapping of USE_MEET (no-op if not present)
  - id: pre-clean-literals
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        gcloud run services update innerpeace-api \
          --region=europe-west2 --project="${PROJECT_ID}" \
          --remove-env-vars=USE_MEET || true

  # Deploy with USE_MEET as a **secret-backed** env
  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        IMG="$(cat /workspace/IMG.txt)"
        gcloud run deploy innerpeace-api \
          --region=europe-west2 --project="${PROJECT_ID}" \
          --image "${IMG}" \
          --service-account "run-innerpeace-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
          --port 8080 --min-instances 1 --max-instances 20 --concurrency 80 --timeout 240 \
          --set-secrets USE_MEET=use-meet-prod:latest \
          --update-env-vars SEND_UPDATES=all,GOOGLE_DELEGATED_USER=thomaspal@innerpeace-developer.co.uk,MANAGER_CALENDAR_ID=thomaspal@innerpeace-developer.co.uk \
          --no-allow-unauthenticated
