options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
timeout: "1200s"

substitutions:
  _REGION: europe-west2
  _SERVICE: innerpeace-api
  _REPO: innerpeace
  _IMAGE: europe-west2-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

steps:
  # 1) Build & push the image
  - id: build-and-push
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -ceu
      - |
        set -o pipefail
        echo "Building $_IMAGE"
        docker build -t "$_IMAGE" .
        docker push "$_IMAGE"
        printf '%s' "$_IMAGE" > /workspace/IMG.txt

  # 2) Pre-clean any existing USE_MEET mapping (literal or secret) — SAFE IF NOT PRESENT
  - id: pre-clean-use-meet
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        set -o pipefail
        gcloud run services update "$_SERVICE" \
          --region="$_REGION" --project="$PROJECT_ID" \
          --remove-env-vars=USE_MEET || true
        gcloud run services update "$_SERVICE" \
          --region="$_REGION" --project="$PROJECT_ID" \
          --remove-secrets=USE_MEET || true

  # 3) Deploy and set USE_MEET from Secret Manager (type stays stable forever)
  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        set -o pipefail
        IMG="$(cat /workspace/IMG.txt)"
        gcloud run deploy "$_SERVICE" \
          --region "$_REGION" \
          --image "$IMG" \
          --service-account "run-innerpeace-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
          --port 8080 \
          --min-instances 1 \
          --max-instances 20 \
          --concurrency 80 \
          --timeout 240 \
          --set-secrets USE_MEET=USE_MEET:latest,CALENDAR_ID=CALENDAR_ID:latest \
          --no-allow-unauthenticated
