# cloudbuild.yaml
substitutions:
  _REGION: europe-west2
  _REPO: apps
  _SERVICE: innerpeace-api
  _IMAGE: europe-west2-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
  _USE_MEET_SECRET: use-meet-prod

steps:
  # Build container
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE", "."]

  # Push to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

  # Idempotent: remove literal USE_MEET if it exists (prevents type-flip failures)
  - name: gcr.io/cloud-builders/gcloud
    id: pre-clean-env
    entrypoint: bash
    args:
      - -c
      - >
        gcloud run services update "$_SERVICE"
        --region="$_REGION" --project="$PROJECT_ID"
        --remove-env-vars=USE_MEET || true

  # Deploy with secret-backed USE_MEET
  - name: gcr.io/cloud-builders/gcloud
    id: deploy
    args:
      [
        "run","deploy","$_SERVICE",
        "--image","$_IMAGE",
        "--region","$_REGION",
        "--project","$PROJECT_ID",
        "--set-secrets","USE_MEET=${_USE_MEET_SECRET}:latest",
        "--update-env-vars","SEND_UPDATES=all,GOOGLE_DELEGATED_USER=thomaspal@innerpeace-developer.co.uk,MANAGER_CALENDAR_ID=thomaspal@innerpeace-developer.co.uk"
      ]

images:
  - $_IMAGE

# <- This is the key line that satisfies Cloud Build when using a custom SA
options:
  logging: CLOUD_LOGGING_ONLY
