# cloudbuild.yaml (deploy section)

substitutions:
  _SERVICE: innerpeace-api
  _REGION: europe-west2
  # your built image tag; keep your existing build that sets this
  _IMAGE: europe-west2-docker.pkg.dev/$PROJECT_ID/apps/innerpeace-api:$SHORT_SHA
  _USE_MEET_SECRET: use-meet-prod

steps:
  # --- your build & push steps remain unchanged ---
  # e.g. docker build/push or pack build

  # PRE-CLEAN: if USE_MEET is currently a literal, remove it (ignore errors)
  - name: gcr.io/cloud-builders/gcloud
    id: pre-clean-env
    entrypoint: bash
    args:
      - -c
      - >
        gcloud run services update "$_SERVICE"
        --region="$_REGION" --project="$PROJECT_ID"
        --remove-env-vars=USE_MEET || true

  # DEPLOY: set USE_MEET from Secret Manager (never a literal again)
  - name: gcr.io/cloud-builders/gcloud
    id: deploy
    args:
      [
        "run","deploy","$_SERVICE",
        "--image","$_IMAGE",
        "--region","$_REGION",
        "--project","$PROJECT_ID",
        "--set-secrets","USE_MEET=${_USE_MEET_SECRET}:latest",
        "--update-env-vars","SEND_UPDATES=all,GOOGLE_DELEGATED_USER=thomaspal@innerpeace-developer.co.uk,MANAGER_CALENDAR_ID=thomaspal@innerpeace-developer.co.uk"
      ]

images:
  - $_IMAGE
